### ISSUE TITLE
Error scanning using sqlite

### ISSUE THREAD

**Issue by therobbiedavis** [zurdi15/romm#114]
I spun up a docker container however it seems like there's an issue when trying to scan. Below is my compose plus the logs.

The primary issue seems to be `sqlite3.OperationalError: disk I/O error`. Not sure how sqlite is suppose to work or be persistent across container reboots as I don't see a volume mapping for a config folder to store the db on the host.

![image](https://user-images.githubusercontent.com/7907265/229584032-4ec2310a-af38-4ca5-b8f3-ddeedce5f54e.png)

```
version: '3'
services:
  romm:
    image: 'zurdi15/romm:latest'
    container_name: romm

    environment:
      - CLIENT_ID=ow0oig7hdxo87q9cq57zstchxxx8sz
      - CLIENT_SECRET=hfn5v9tcnui4jqkng7ndqktzj0i3p0
    volumes:
      - '/root/Server/mnt/media_merge/:/library'
      - '/root/Server/.config/romm/config.yml:/romm/config.yml'
    ports:
      - '9999:80'
    networks:
      - proxy-default
      - default
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
networks:
  proxy-default:
    name: proxy_default
    external: true
  default:
  ```
[_romm_logs.txt](https://github.com/zurdi15/romm/files/11140058/_romm_logs.txt)
