### ISSUE TITLE
[Other] Clean up old container files

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#135]
How to clean up the old files generated prior the v1.6.1?
OR move them to the new locations?

**Comment by zurdi15** [comment]
What do you mean by old files? if you mean the resources files you can just move them wherever you want and re-bind them to the new internal path `/romm/resources``

**Comment by XargonWan** [comment]
I added the /romm mount to my docker-compose, so now my database is empty, but all the downloaded data and stuff I believe that is still somwhere in my fs.

**Comment by XargonWan** [comment]
Moreover I think that's wrong:

'/path/to/config.yml:/romm/config.yml'

in my case it generated an empty folder called "config.yml"

My compose:

```
  romm:
    image: 'zurdi15/romm:latest'
    container_name: romm
    environment:
      - CLIENT_ID=foo
      - CLIENT_SECRET=bar
      - STEAMGRIDDB_API_KEY=WIP
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - '/my/roms/location:/library'
      - './config/romm:/romm'
    ports:
      - '45107:80'
    restart: "unless-stopped"
```
