### ISSUE TITLE
[Other] Config file ignored

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#160]
Seems like my config.yml is being ignored, any help?
After adding the config the container was restared (and the new version applied) and I did a full scan.

```yml
  romm:
    image: 'zurdi15/romm:latest'
    container_name: romm
    environment:
      - CLIENT_ID=foo
      - CLIENT_SECRET=bar
      - STEAMGRIDDB_API_KEY=WIP
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - '/media/merged/emulazione:/romm/library'
      - './config/romm:/romm'
      - './config/romm/config.yml:/romm/config.yml'
    ports:
      - '45107:80'
    restart: "unless-stopped"
```

`-rwxrwxrwx 1 root root 218 Apr 12 14:27 config/romm/config.yml`
```yml
exclude:
  files:
    - 'wget-log'
    - 'gamelist.xml'
    - 'sync.ffs_lock'
    - '.old'
    - '.bak' 
  folders:
    - 'images'
    - 'manuals'
    - 'videos'
    - 'DLCs'
    - 'mods'
    - 'iwads'
    - 'WHDLoad'
```

![image](https://user-images.githubusercontent.com/6771419/231500394-1e2794c7-be3d-4fb0-bd0a-5c11e57b6af7.png)
