### ISSUE TITLE
[Bug] docker-compose: Exit with code 3

### ISSUE THREAD

**Issue by IngwiePhoenix** [zurdi15/romm#220]
**RomM version**
`image: 'zurdi15/romm:latest'`

**Describe the bug**
When I try to launch the container, it ends with an error code 3. I have tried to reset the container and gone ahead and delete adjanced files, but the same happens every time.

**To Reproduce**
1. Create `docker-compose.yml` (mine is below)
2. Create `data/config.yml` (also below)
3. `docker-compose up`

**Expected behavior**
I expected to see something logged akin to the server starting up so I could see if it can properly read my test data.

**Screenshots**
No screenshots - but some terminal copypasta :)

`docker-compose.yml`:
```yml
version: '3'
services:
  romm:
    image: 'zurdi15/romm:latest'
    container_name: romm
    environment:
      - ROMM_DB_DRIVER="sqlite" # This variable can be set as: mariadb | sqlite. If it is not defined, sqlite will be the database by default
      - DB_HOST=romm_db # Only if ROMM_DB_DRIVER='mariadb'
      - DB_PORT=3306 # Only if ROMM_DB_DRIVER='mariadb'
      - DB_USER=romm-user # Only if ROMM_DB_DRIVER='mariadb'
      - DB_NAME=romm # Only if ROMM_DB_DRIVER='mariadb'. Can be optionally changed, and should match the MYSQL_DATABASE value in the mariadb container.
      - DB_PASSWD=change-me # Only if ROMM_DB_DRIVER='mariadb'
      - CLIENT_ID=xxx
      - CLIENT_SECRET=xxx
      - STEAMGRIDDB_API_KEY=WIP
    volumes:
      - '/mnt/diskstation/bunker/Retro:/romm/library'
      - '/mnt/diskstation/bunker/Services/romm/resources:/romm/resources'
      - './data/config.yml:/romm/config.yml'
      - './data/database:/romm/database' # Only if ROMM_DB_DRIVER='sqlite' or ROMM_DB_DRIVER not exists
    ports:
      - '8484:80'
    #depends_on:
    #  - romm_db
    #restart: "unless-stopped"

  # Only if ROMM_DB_DRIVER='mariadb'
  #romm_db:
  #  image: lscr.io/linuxserver/mariadb:latest
  #  container_name: romm_db
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=RootPasswordChangeMe
  #    - MYSQL_DATABASE=romm
  #    - MYSQL_USER=romm-user
  #    - MYSQL_PASSWORD=change-me
  #  volumes:
  #    - ./config:/config
  #  ports:
  #    - 3306:3306
  #  restart: "unless-stopped"
```

`data/config.yml`:
```yml
exclude:
  # Exclude platforms to be scanned
  platforms:
    - 'romm'
    - 'swf'

  # Exclude roms or parts of roms to be scanned
  roms:
    ## Single file games section
    single_file:
      # Exclude matched file names to be sanned
      names:
        - 'info.txt'
      # Exclude all files with certain extensions to be scanned
      extensions:
        - 'xml'
        - 'nfo'

    ## Multi files games section
    multi_file:
      # Exclude matched 'folder' (RomM identifies folders as multi file games) names to be scanned
      names:
        - 'my_multi_file_game'
        - 'DLC'
      parts:
        # Exclude matched file names to be sanned from multi file roms
        # Keep in mind that RomM doesn't scan folders inside multi files games,
        # so there is no need to exclude folders from inside of multi files games.
        names:
          - 'data.xml'
        # Exclude all files with certain extensions to be scanned from multi file roms
        extensions:
          - 'txt'
          - 'nfo'

# Asociate different platform names to your current file system platform names
system:
  platforms:
    # [your custom platform folder name]: [RomM platform name]
    Dreamcast: 'dc'
    GameCube: 'ngc'
    ps1: 'ps'
    psv: 'psvita'
    'Sega Saturn': 'saturn'
```

Output:
```
# docker-compose up
[+] Running 1/0
 ⠿ Container romm  Created                                                                                                                                                                       0.0s
Attaching to romm
romm exited with code 3
```

**Desktop (please complete the following information):**
 - OS: Linux (OpenWrt 22.03 as FriendlyWrt on FriendlyElec NanoPi R6s (aarch64/armv8))
 - Browser: Didn't even get there...
 - Version: n/a

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser: n/a
 - Version: n/a
 

*Additional context**
I set up a very simple example. The library linked above looks like this:

```
# tree -a /mnt/diskstation/bunker/Retro/
/mnt/diskstation/bunker/Retro/
└── ROMs
    └── GB
        ├── Dr. Mario.GB
        ├── KIRBY.GB
        ├── Pac-In-Time (USA) (SGB Enhanced).gb
        ├── Pokemon - Gelbe Edition [GER].gb
        ├── Pokemon - Rote Edition [GER].gb
        ├── Pokémon - Blaue Edition [EU GER].gb
        ├── Super Mario Land 2.gb
        ├── Super Mario Land 3.gb
        ├── Super Pika Land.gb
        └── Tetris.gb

2 directories, 10 files
```

`/mnt/diskstation` is a NFS mount to a Synology NAS holding practically all my data. The NFS UID/GIDs are not mapped, but the container is ran as root. Other containers handle this fine - so technically this shouldn't be an option. Well...technically.
