### ISSUE TITLE
[Feature] Enhance folder recognition

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#244]
In my config I got:
```yml
# Asociate different platform names to your current file system platform names
system:
  platforms:
    # [your custom platform folder name]: [RomM platform name]
    gc: 'ngc' # In this example if you have a 'gc' folder, RomM will treat it like the 'ngc' folder
    psx: 'ps' # In this example if you have a 'psx' folder, RomM will treat it like the 'ps' folder         
    atarilynx: 'lynx'
    dreamcast: 'dc'
    mastersystem: 'sms'
    megadrive: 'genesis-slash-megadrive'
    n3ds: '3ds'
    pcengine: 'pce'
    wonderswancolor: 'wonderswan-color'
    gameandwatch: 'gw'
    gamegear: 'gg'
```

but a better config can be:

```yml
# Asociate different platform names to your current file system platform names
system:
  platforms:
    # [RomM platform name] : [your custom platforms folder names]
 folder         
    lynx: [atarilynx, alynx, atari-lynx]
    dc: [dreamcast, segadc]
    sms: [mastersystem, ms]
```

Basically in this edit of mine we got the romm naming convention first, and then the possible folder to search in.
So every user can even contribute by adding their naming convention, romm can iterate this list and stop whenever it found the correct folder name (as no one usually got two folder for the same system).
In this way you can ship a config that doesn't require any user action on the folders side as probably their naming conventions are already met.
If not they can be added.

Common naming convention can be taken from:
- retropie
- batocera
- retrobat
- emulationstation desktop edition (used by RetroDECK as well)
- amberelec
- user poll?
