### ISSUE TITLE
[Bug] 524bytes files in every game i try to download

### ISSUE THREAD

**Issue by OuterWinnie** [zurdi15/romm#297]
**RomM version**
1.8.4 - Docker

**Describe the bug**
When i press download, it downloads an 524bytes files, and not the whole game. I don't see any error in the docker log. If i try to download the file from the mobile, it downloads an html.

**To Reproduce**
1. Click on download
2. Check the filesize

**Expected behavior**
It should download the complete file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 11 "Bullseye"
 - Browser: Edge

**Comment by OuterWinnie** [comment]
> Did you just setup RomM or is this new behaviour you're seeing? And can you post the romm part of your docker-compose.yml (or docker command)?

It was working at the beggining, but it isn't anymore. The only thing i have done is adding more games. I'm using an stack like this:

`version: '3'
volumes:
  mysql_data:
services:
  romm:
    image: zurdi15/romm:latest
    container_name: romm
    environment:
      - ROMM_DB_DRIVER=sqlite # This variable can be set as: mariadb | sqlite. If it is not defined, sqlite will be the database by default
      - CLIENT_ID=wck57odxfpi2kzdi5zvmyzu3ubrfwx
      - CLIENT_SECRET=483t3vwczyhxx1v29evuuj330l7w6t
      - STEAMGRIDDB_API_KEY=ce708353cbe3554a8a132c0099eccb43
    volumes:
      - '/mnt/Elements/Share/Games:/romm/library/roms'
      - '/home/pi/docker/data/romm/resources:/romm/resources'
      - '/home/pi/docker/data/romm/config.yml:/romm/config.yml'
      - '/home/pi/docker/data/romm/database:/romm/database' # Only needed if ROMM_DB_DRIVER=sqlite or ROMM_DB_DRIVER not exists 
    ports:
      - 80:80

    restart: "unless-stopped"`

**Comment by GAntoine** [comment]
Ok your docker-compose looks right. How many games did you add, and how many do you have in total?

Easiest things to try is `docker-compose restart romm` and, if that didn't work:

```
docker-compose stop romm
docker-compose remove romm
docker-compose up -d romm
```

**Comment by OuterWinnie** [comment]
I have tried rebooting, and remade it from zero, and i get the same problem.

**Comment by GAntoine** [comment]
Could you upload the 524 byte file here so I can take a look at it?

**Comment by OuterWinnie** [comment]
Here it is:
[Advance Wars.zip](https://github.com/zurdi15/romm/files/12099139/Advance.Wars.zip)

**Comment by GAntoine** [comment]
Alright so when I change the extension from .gba to .html, it loads the base HTML file that renders RomM, which is why you're seeing that behaviour on mobile. My guess if `LIBRARY_BASE_PATH` is misconfigured, so it can't find the file and defaults to an empty response.

Can you post an image of the download request, like this?

<img width="549" alt="Screenshot 2023-07-19 at 3 19 53 PM" src="https://github.com/zurdi15/romm/assets/3247106/f0912d75-086a-43d8-9fa1-52308000c196">

**Comment by OuterWinnie** [comment]
Yep, here it is:

![image](https://github.com/zurdi15/romm/assets/6392320/8a3aea59-4d1e-4545-8529-e4e866d33b0d)

**Comment by GAntoine** [comment]
Ah! Ok could you try cleaning the cache in your browser (Application > Storage > Clear site data)? I also see the folder for your games is `GBA` (all caps); is that set in the RomM config file?

Sorry for all the questions, this is one of a hand full of bug reports so we're trying to figure out what tends to break and how best to report it.

**Comment by OuterWinnie** [comment]
Tried clearing the site data, and same problem. Here is the config.yml:
[config.zip](https://github.com/zurdi15/romm/files/12099826/config.zip)

**Comment by GAntoine** [comment]
Well I'm out of ideas, we haven't released in a few months so I don't expect it's a code change that caused this. My instance has 1500+ files and downloads things as expected. I'm going to leave this pending and take another stab at it another time, but do let us know if you manage to fix it.

**Comment by OuterWinnie** [comment]
Thanks either way!

**Comment by stephanschorer** [comment]
I have the same issue, each download has 524 MB

**Comment by GAntoine** [comment]
@stephanschorer 524 MB, KB or B? If it's bytes my guess is it's the same issue as above, which you can check by changing one of the file to html and opening it in the browser (you should see `<div id="app"></div>` in the inspector).

On that note, could you post the relevant part of your docker-compose file?

**Comment by stephanschorer** [comment]
@GAntoine oh sorry I meant 512 B and yes there is this div inside

docker-compose.yaml

```
services:
  romm:
    image: zurdi15/romm:latest
    container_name: romm
    environment:
      - ROMM_DB_DRIVER=sqlite # This variable can be set as: mariadb | sqlite. If it is not defined, sqlite will be the database by default
      #- DB_HOST=mariadb # Only needed if ROMM_DB_DRIVER=mariadb
      #- DB_PORT=3306 # Only needed if ROMM_DB_DRIVER=mariadb
      #- DB_USER=romm-user # Only needed if ROMM_DB_DRIVER=mariadb
      #- DB_NAME=romm # Only needed if ROMM_DB_DRIVER=mariadb. Can be optionally changed, and should match the MYSQL_DATABASE value in the mariadb container.
      #- DB_PASSWD=<database password> # Only needed if ROMM_DB_DRIVER=mariadb
      - CLIENT_ID=*REDACTED*
      - CLIENT_SECRET=*REDACTED*
      - STEAMGRIDDB_API_KEY=*REDACTED*
    volumes:
      - './library:/romm/library'
      - './resources:/romm/resources'
      - './config.yml:/romm/config.yml'
      - './database:/romm/database' # Only needed if ROMM_DB_DRIVER=sqlite or ROMM_DB_DRIVER not exists 
    #ports:
    #  - 80:80
    #depends_on:
    #  - romm_db
    restart: "unless-stopped"
    networks:
      - services_default
      - nginx_default
```

as you can see the service is behind a reverse proxy
