### ISSUE TITLE
[Bug] Non-Graceful Failure When Scanning Unsupported Platforms

### ISSUE THREAD

**Issue by shuttle128** [zurdi15/romm#346]
**RomM version**
dev-1.10

**Describe the bug**
When scanning library, if the function get_roms runs into a folder that is for an unsupported platform (in this case Gamecube), the script throws an exception and stops scanning the library.

**To Reproduce**
1. Have a folder in the library with a folder name that is not named the same as a supported platform.
2. Go to Library>Scan>Scan
3. Interface shows scanning in progress and creates a platform entry for the unsupported platform.
4. Library scan appears to still be scanning on the page, but checking the logs, the scan has failed with exception.
5. Error logs below

**Expected behavior**
Expected any platforms that are unsupported to be ignored or an exception thrown with the option of user interaction to skip unsupported platforms. 

**Desktop (please complete the following information):**
 - Server OS: Ubuntu Server 20.04

**Additional context**
The supported platforms are not easily found in the Platform Support section of the Readme. I missed this information several times because it was hidden in a collapsed table. I expected to be able to transfer over most of my EmuDeck folder structure and RomM would handle scraping the metadata since one of the features states "EmuDeck folder structure compatibility." I moved my entire EmuDeck folders to the RomM library folder and it has failed this way on several folders so far.

```
INFO:     connection closed
INFO:     10.222.214.124:0 - "GET /platforms HTTP/1.0" 200 OK
INFO:     10.222.214.124:0 - "GET /platforms/gamecube/roms?cursor=&size=60&search_term= HTTP/1.0" 200 OK
INFO:     ('127.0.0.1', 44860) - "WebSocket /socket.io/?EIO=4&transport=websocket" [accepted]
INFO:     connection open
INFO:	  [RomM][2023-08-17 23:05:38] 🔎 Scanning 
INFO:	  [RomM][2023-08-17 23:05:38] · gamecube
WARNING:  [RomM][2023-08-17 23:05:38]   gamecube not found in IGDB
Task exception was never retrieved
future: <Task finished name='Task-1230' coro=<AsyncServer._handle_event_internal() done, defined at /usr/local/lib/python3.10/dist-packages/socketio/asyncio_server.py:522> exception=Roms not found for platform gamecube. Check RomM folder structure here: https://github.com/zurdi15/romm#-folder-structure>
Traceback (most recent call last):
  File "/back/utils/fs.py", line 226, in get_roms
    fs_single_roms: list[str] = list(os.walk(roms_file_path))[0][2]
IndexError: list index out of range
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/socketio/asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.10/dist-packages/socketio/asyncio_server.py", line 558, in _trigger_event
    ret = await handler(*args)
  File "/back/endpoints/scan.py", line 88, in scan_handler
    await scan_platforms(platforms, complete_rescan)
  File "/back/endpoints/scan.py", line 48, in scan_platforms
    fs_roms = fs.get_roms(scanned_platform.fs_slug)
  File "/back/utils/fs.py", line 228, in get_roms
    raise RomsNotFoundException(p_slug) from exc
utils.exceptions.RomsNotFoundException: Roms not found for platform gamecube. Check RomM folder structure here: https://github.com/zurdi15/romm#-folder-structure
```

**Comment by zurdi15** [comment]
Can you share the folder structure? I am triying to reproduce your error but for me it is working as intended.

```
 Scanning 
INFO:     [RomM][2023-08-18 08:33:19] · PSP
INFO:     [RomM][2023-08-18 08:33:20]   Identified as PlayStation Portable 🎮
INFO:     [RomM][2023-08-18 08:33:20] · gamecube
WARNING:  [RomM][2023-08-18 08:33:20]   gamecube not found in IGDB
INFO:     [RomM][2023-08-18 08:33:20] · no_platform
WARNING:  [RomM][2023-08-18 08:33:21]   no_platform not found in IGDB
INFO:     [RomM][2023-08-18 08:33:21]    · game.iso
ERROR:    [RomM][2023-08-18 08:33:22] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/games/
ERROR:    [RomM][2023-08-18 08:33:22] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/games/
ERROR:    [RomM][2023-08-18 08:33:23] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/games/
WARNING:  [RomM][2023-08-18 08:33:25]      game.iso not found in IGDB
INFO:     [RomM][2023-08-18 08:33:25] · gb
INFO:     [RomM][2023-08-18 08:33:25]   Identified as Game Boy 🎮
```

**Comment by shuttle128** [comment]
Here's my folder structure for the main RomM app config directory on my main OS drive:

```
shuttle128@homeserver:~/docker/appdata/romm$ tree -p -u
[drwxrwxr-x shuttle128   ]  .
├── [-rwxrwxr-x shuttle128   ]  config.yml
├── [drwxrwxr-x shuttle128   ]  database
│   └── [-rwxrwxr-x shuttle128   ]  romm.db
└── [drwxrwxr-x shuttle128   ]  logs
    ├── [-rwxrwxr-x shuttle128   ]  20230815_182806.log
    ├── [-rwxrwxr-x shuttle128   ]  20230815_182807.log
    ├── [-rwxrwxr-x shuttle128   ]  20230818_043717.log
    ├── [-rwxrwxr-x shuttle128   ]  20230818_043719.log
    ├── [-rw-rw-r-- root    ]  20230818_045911.log
    ├── [-rw-rw-r-- root    ]  20230818_045912.log
    ├── [-rw-rw-r-- root    ]  20230818_163113.log
    └── [-rw-rw-r-- root    ]  20230818_163114.log
```
Here is the folder structure for my library directory on a 8 TB Raid5 array:

```
shuttle128@homeserver:/mnt/raid5/media/Games/roms$ tree -p -u
[drwxrwxr-x shuttle128   ]  .
├── [drwxrwxr-x shuttle128   ]  3ds
│   ├── [-rw-r--r-- shuttle128   ]  game1.cia
│   ├── [-rw-r--r-- shuttle128   ]  systeminfo.txt
│   ├── [-rwxrwxrwx shuttle128   ]  game2.3dz
│   └── [-rwxrwxrwx shuttle128   ]  game3.3ds
├── [drwxrwxr-x shuttle128   ]  dos
│   ├── [-rwxrwxrwx shuttle128   ]  game1.zip
│   └── [-rw-r--r-- shuttle128   ]  systeminfo.txt
├── [drwxrwxr-x shuttle128   ]  gamecube
│   ├── [-rwxrwxrwx shuttle128   ]  game1
│       ├── [-rwxrwxrwx shuttle128   ]  game1 disc 1.iso
│       └── [-rwxrwxrwx shuttle128   ]  game1 disc 2.iso
│   ├── [-rw-r--r-- shuttle128   ]  systeminfo.txt
│   ├── [-rw-r--r-- shuttle128   ]  game2.gct
│   └── [-rw-r--r-- shuttle128   ]  game3.iso
├── [drwxrwxr-x shuttle128   ]  gamegear
│   ├── [-rwxrwxrwx shuttle128   ]  game1.sms
│   ├── [-rw-r--r-- shuttle128   ]  systeminfo.txt
│   └── [-rwxrwxrwx shuttle128   ]  game2.gg
├── [drwxrwxr-x shuttle128   ]  gb
│   ├── [-rwxrwxrwx shuttle128   ]  game1.gb
│   ├── [-rwxrwxrwx shuttle128   ]  game2.gb
│   └── [-rw-r--r-- shuttle128   ]  systeminfo.txt
├── [drwxrwxr-x shuttle128   ]  gba
│   ├── [-rw-r--r-- shuttle128   ]  game1.gba
│   ├── [-rw-r--r-- shuttle128   ]  systeminfo.txt
│   └── [-rwxrwxrwx shuttle128   ]  game2.gba
├── [drwxrwxr-x shuttle128   ]  gbc
│   ├── [-rwxrwxrwx shuttle128   ]  game1.gbc
│   ├── [-rw-r--r-- shuttle128   ]  systeminfo.txt
│   └── [-rwxrwxrwx shuttle128   ]  game2.gbc
├── [drwxrwxr-x shuttle128   ]  n64
│   ├── [-rw-r--r-- shuttle128   ]  game1.z64
│   ├── [-rwxrwxrwx shuttle128   ]  game2.v64
│   └── [-rw-r--r-- shuttle128   ]  systeminfo.txt
├── [drwxrwxr-x shuttle128   ]  nds
│   ├── [-rwxrwxr-x shuttle128   ]  game1.nds
│   ├── [-rwxrwxr-x shuttle128   ]  game2.zip
│   ├── [-rw-r--r-- shuttle128   ]  game3.cia
│   ├── [-rw-r--r-- shuttle128   ]  systeminfo.txt
│   └── [-rwxrwxr-x shuttle128   ]  game4.rar
├── [drwxrwxr-x shuttle128   ]  nes
│   ├── [-rwxrwxrwx shuttle128   ]  game1.zip
│   ├── [-rw-r--r-- shuttle128   ]  systeminfo.txt
│   └── [-rwxrwxrwx shuttle128   ]  game2.NES
├── [drwxrwxr-x shuttle128   ]  ps2
│   ├── [-rwxrwxr-x shuttle128   ]  game1.rar
│   ├── [-rw-r--r-- shuttle128   ]  systeminfo.txt
│   └── [-rwxrwxr-x shuttle128   ]  game2.iso
├── [drwxrwxr-x shuttle128   ]  ps3
│   ├── [-rw-r--r-- shuttle128   ]  game1.iso
│   ├── [-rw-r--r-- shuttle128   ]  systeminfo.txt
│   └── [-rw-r--r-- shuttle128   ]  game2.iso
├── [drwxrwxr-x shuttle128   ]  psp
│   ├── [-rwxrwxrwx shuttle128   ]  game1.cso
│   ├── [-rwxrwxrwx shuttle128   ]  game2.iso
│   ├── [-rwxrwxr-x shuttle128   ]  game3.zip
│   └── [drwxrwxr-x shuttle128   ]  game4
│       └── [-rwxrwxrwx shuttle128   ]  EBOOT.PBP
├── [drwxrwxr-x shuttle128   ]  psvita
│   ├── [-rw-r--r-- shuttle128   ]  game1.zip
│   └── [-rw-r--r-- shuttle128   ]  systeminfo.txt
├── [drwxrwxr-x shuttle128   ]  scummvm
│   ├── [-rw-r--r-- shuttle128   ]  game1.7z
│   └── [-rw-r--r-- shuttle128   ]  systeminfo.txt
├── [drwxrwxr-x shuttle128   ]  segacd
│   ├── [-rw-r--r-- shuttle128   ]  game1.zip
│   └── [-rw-r--r-- shuttle128   ]  systeminfo.txt
├── [drwxrwxr-x shuttle128   ]  snes
│   ├── [-rwxrwxrwx shuttle128   ]  game1.SMC
│   └── [-rwxrwxrwx shuttle128   ]  game2.smc
├── [drwxrwxr-x shuttle128   ]  switch
│   ├── [-rw-r--r-- shuttle128   ]  rom1.nsp
│   └── [-rw-r--r-- shuttle128   ]  rom2.nsp
├── [-rw-r--r-- shuttle128   ]  systems.txt
├── [drwxrwxr-x shuttle128   ]  wii
│   ├── [-rw-r--r-- shuttle128   ]  game1.iso
│   └── [-rw-r--r-- shuttle128   ]  game2.iso
├── [drwxrwxr-x shuttle128   ]  wiiu
│   ├── [-rw-r--r-- shuttle128   ]  game1.wux
│   └── [-rw-r--r-- shuttle128   ]  systeminfo.txt
└── [drwxrwxr-x shuttle128   ]  xbox
    ├── [-rw-rw-r-- shuttle128   ]  game1.zip
    ├── [-rw-rw-r-- shuttle128   ]  game2.zip
    └── [-rw-r--r-- shuttle128   ]  systeminfo.txt
```

and here is the romm excerpt from my docker compose file:

```
  romm:
    image: zurdi15/romm:dev-latest
    container_name: romm
    networks:
      npm_proxy:
        ipv4_address: 192.168.89.120
    environment:
      - ROMM_DB_DRIVER=sqlite
      - CLIENT_ID=xxxxxxxxxxxxxx
      - CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxx
      - STEAMGRIDDB_API_KEY=xxxxxxxxxxxxxxxxxxxxx
    volumes:
      - '$DATADIR/media/Games/roms:/romm/library'
      - '$DATADIR/media/Games/resources' # [Optional] Path where roms metadata (covers) are stored
      - '$DOCKERDIR/appdata/romm/config.yml:/romm/config.yml' # [Optional] Path where config is stored
      - '$DOCKERDIR/appdata/romm/database:/romm/database' # [Optional] Only needed if ROMM_DB_DRIVER=sqlite or ROMM_DB_DRIVER not exists 
      - '$DOCKERDIR/appdata/romm/logs:/romm/logs'
    ports:
      - "1337:80"
    depends_on:
      - romm_db
    restart: "unless-stopped"
```

from my .env file:

```
DOCKERDIR="/home/shuttle128/docker"
DATADIR="/mnt/raid5"
```

here is my romm config.yml:

```
exclude:
  # Exclude platforms to be scanned
  platforms:
    - 'romm'

  # Exclude roms or parts of roms to be scanned
  roms:
    ## Single file games section
    single_file:
      # Exclude matched file names to be sanned
      names:
        - 'systeminfo.txt'
      # Exclude all files with certain extensions to be scanned
      extensions:
        - 'xml'
        - 'txt'

    ## Multi files games section
    multi_file:
      # Exclude matched 'folder' (RomM identifies folders as multi file games) names to be scanned
      names:
        - 'DLC'
      parts:
        # Exclude matched file names to be sanned from multi file roms
        # Keep in mind that RomM doesn't scan folders inside multi files games,
        # so there is no need to exclude folders from inside of multi files games.
        names:
          - 'systeminfo.txt'
        # Exclude all files with certain extensions to be scanned from multi file roms
        extensions:
          - 'txt'
          - 'xml'

# Asociate different platform names to your current file system platform names
system:
  platforms:
    # [your custom platform folder name]: [RomM platform name]
#    gc: 'ngc' # In this example if you have a 'gc' folder, RomM will treat it like the 'ngc' folder
#    psx: 'ps' # In this example if you have a 'psx' folder, RomM will treat it like the 'ps' folder
```

I run docker compose from my user account but all containers seem to run in root internal to the container. I've changed some directory permissions to my user to allow moving files around from my normal account.
