### ISSUE TITLE
[Feature] Load IGDB id/secret from file

### ISSUE THREAD

**Issue by rthill91** [zurdi15/romm#492]
**Is your feature request related to a problem? Please describe.**
I don't like to put secrets directly in my docker-compose file and I'd rather not have to.

**Describe the solution you'd like**
I would love to have the additional (optional) environment variables `IGDB_CLIENT_ID_FILE` and `IGDB_CLIENT_SECRET_FILE` such that my docker-compose file could look something like
```yaml
secrets:
  igdb_id:
    file: ./igdb_id
  igdb_secret:
    file: ./igdb_secret

services:
  romm:
    ...
    secrets:
      - igdb_id
      - igdb_secret
    environment:
      - IGDB_CLIENT_ID_FILE=/run/secrets/igdb_id
      - IGDB_CLIENT_SECRET_FILE=/run/secrets/igdb_secret
```
_similar to [traefik config](https://doc.traefik.io/traefik/user-guides/docker-compose/acme-dns/#use-secrets)_

**Describe alternatives you've considered**
N/A

**Additional context**
I've done a cursory look through how config is loaded and I _think_ this would be a very easy feature to add with something like
```py3
# IGDB
_igdb_client_id: str = os.environ.get("IGDB_CLIENT_ID", os.environ.get("CLIENT_ID", ""))
_igdb_client_secret: str = os.environ.get(
    "IGDB_CLIENT_SECRET", os.environ.get("CLIENT_SECRET", "")
)
if not _igdb_client_id:
    if (
        _igdb_client_id_file := os.environ.get("IGDB_CLIENT_ID_FILE", "")
    ) and os.path.exists(_igdb_client_id_file):
        with open(_igdb_client_id_file) as fh:
            _igdb_client_id = fh.readline().strip()
if not _igdb_client_secret:
    if (
        _igdb_client_secret_file := os.environ.get("IGDB_CLIENT_SECRET_FILE", "")
    ) and os.path.exists(_igdb_client_secret_file):
        with open(_igdb_client_secret_file) as fh:
            _igdb_client_secret = fh.readline().strip()
IGDB_CLIENT_ID: Final = _igdb_client_id
IGDB_CLIENT_SECRET: Final = _igdb_client_secret
```
though admittedly I've done almost no real testing of it.

**Comment by gantoine** [comment]
You shouldn't keeps secrets in the docker-compose file directly, instead use an `.env` file stored in the same directory:

`docker-compose.yml`
```
services:
  romm:
    ...
    env_file: .env
    environment:
      - IGDB_CLIENT_ID=$IGDB_CLIENT_ID
      - IGDB_CLIENT_SECRET=$IGDB_CLIENT_SECRET
```

`.env`
```
IGDB_CLIENT_ID=XXXXXXXXXXXXX
IGDB_CLIENT_SECRET=XXXXXXXXXXXX
```
