### ISSUE TITLE
[Bug] [Errno 98] Address in use when using docker MACVLAN

### ISSUE THREAD

**Issue by Marcus-Schubert** [zurdi15/romm#494]
**RomM version**
zurdi15/romm:latest

**Describe the bug**
When using MACVLAN in docker, I run into the error `[Errno 98] Address in use` although the assigned IP address is not in use. I can see that the IP is assigned for a short moment but then the container loses the IP.

I use the following compose file:

```
version: "3"
services:
  romm:
    image: zurdi15/romm:latest
    container_name: romm
    networks:
            default:
                ipv4_address: 192.168.178.120
    environment:
      - ROMM_DB_DRIVER=sqlite # mariadb | sqlite (default: sqlite)
      - IGDB_CLIENT_ID=xxx
      - IGDB_CLIENT_SECRET=xxx
      # [Optional - WIP] Use SteamGridDB as a source for covers
      # - STEAMGRIDDB_API_KEY=<SteamGridDB api key>
    volumes:
      - /srv/dev-disk-by-label-Data/games/ROMs:/path/to/library:/romm/library
      - /srv/dev-disk-by-label-Data/romm-res:/path/to/resources:/romm/resources # [Optional] Path where roms metadata (covers) are stored
      - /srv/dev-disk-by-label-Data/romm-conf/config.yml:/path/to/config.yml:/romm/config.yml # [Optional] Path where config is stored
      - /srv/dev-disk-by-label-Data/romm-db:/path/to/database:/romm/database # [Optional] Only needed if ROMM_DB_DRIVER=sqlite or not set
      - /srv/dev-disk-by-label-Data/romm-logs:/path/to/logs:/romm/logs # [Optional] Path where logs are stored
    ports:
      - 80:8080
    restart: "unless-stopped"

networks:
    default:
        external:
            name: home
```

**To Reproduce**
1. Set up docker compose file in MACVLAN environment
2. Launch service
3. See error, those 4 lines are repeated over and over again

```
ERROR:    [Errno 98] Address in use
INFO:     [RomM][alembic.runtime.migration] Context impl SQLiteImpl.
INFO:     [RomM][alembic.runtime.migration] Will assume non-transactional DDL.
WARNING:  [RomM][2023-12-09 12:49:34] Twitch token invalid: fetching a new one...
```

**Expected behavior**
Service is launched correctly
