### ISSUE TITLE
Background tasks not enabled in the UI

### ISSUE THREAD

**Issue by daedric7** [zurdi15/romm#530]
**RomM version**
zurdi15/romm:latest at the time of this issue

**Describe the bug**
Attempting to import ARCADE games floods the logs with:

```
romm     | INFO:          [RomM][2023-12-29 19:30:38] Scheduled mame xml update started...
romm     | ERROR:         [RomM][2023-12-29 19:30:38] Scheduled mame xml update failed
romm     | Traceback (most recent call last):
romm     |   File "/backend/handler/igdb_handler.py", line 202, in get_rom
romm     |     with open(MAME_XML_FILE, "r") as index_xml:
romm     | FileNotFoundError: [Errno 2] No such file or directory: '/backend/handler/fixtures/mame.xml'
romm     |
romm     | During handling of the above exception, another exception occurred:
romm     |
romm     | Traceback (most recent call last):
romm     |   File "/backend/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
romm     |     sock = connection.create_connection(
romm     |   File "/backend/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
romm     |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
romm     |   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
romm     |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
romm     | socket.gaierror: [Errno -2] Name does not resolve
romm     |
romm     | The above exception was the direct cause of the following exception:
romm     |
romm     | Traceback (most recent call last):
romm     |   File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
romm     |     response = self._make_request(
romm     |   File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 492, in _make_request
romm     |     raise new_e
romm     |   File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 468, in _make_request
romm     |     self._validate_conn(conn)
romm     |   File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
romm     |     conn.connect()
romm     |   File "/backend/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
romm     |     self.sock = sock = self._new_conn()
romm     |   File "/backend/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
romm     |     raise NameResolutionError(self.host, self, e) from e
romm     | urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7fb0f4d250f0>: Failed to resolve 'hyperlist.hyperspin-fe.com' ([Errno -2] Name does not resolve)
romm     |
romm     | The above exception was the direct cause of the following exception:
romm     |
romm     | Traceback (most recent call last):
romm     |   File "/backend/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
romm     |     resp = conn.urlopen(
romm     |   File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
romm     |     retries = retries.increment(
romm     |   File "/backend/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
romm     |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
romm     | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='hyperlist.hyperspin-fe.com', port=443): Max retries exceeded with url: /genall.php?system=6 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb0f4d250f0>: Failed to resolve 'hyperlist.hyperspin-fe.com' ([Errno -2] Name does not resolve)"))
romm     |
romm     | During handling of the above exception, another exception occurred:
romm     |
romm     | Traceback (most recent call last):
romm     |   File "/backend/tasks/utils.py", line 95, in run
romm     |     response = requests.get(self.url)
romm     |   File "/backend/lib/python3.10/site-packages/requests/api.py", line 73, in get
romm     |     return request("get", url, params=params, **kwargs)
romm     |   File "/backend/lib/python3.10/site-packages/requests/api.py", line 59, in request
romm     |     return session.request(method=method, url=url, **kwargs)
romm     |   File "/backend/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
romm     |     resp = self.send(prep, **send_kwargs)
romm     |   File "/backend/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
romm     |     r = adapter.send(request, **kwargs)
romm     |   File "/backend/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
romm     |     raise ConnectionError(e, request=request)
romm     | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hyperlist.hyperspin-fe.com', port=443): Max retries exceeded with url: /genall.php?system=6 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb0f4d250f0>: Failed to resolve 'hyperlist.hyperspin-fe.com' ([Errno -2] Name does not resolve)"))
romm     | ERROR:         [RomM][2023-12-29 19:30:38] HTTPSConnectionPool(host='hyperlist.hyperspin-fe.com', port=443): Max retries exceeded with url: /genall.php?system=6 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb0f4d250f0>: Failed to resolve 'hyperlist.hyperspin-fe.com' ([Errno -2] Name does not resolve)"))
romm     | ERROR:         [RomM][2023-12-29 19:30:38] Could not fetch the MAME XML file from HyperspinFE

```

**To Reproduce**
1. Have arcade roms
2. Click Scan
3. Start scanning

**Comment by daedric7** [comment]
Oh, if it helps:

Server:

```
dig hyperlist.hyperspin-fe.com

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> hyperlist.hyperspin-fe.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 21974
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;hyperlist.hyperspin-fe.com.    IN      A

;; AUTHORITY SECTION:
hyperspin-fe.com.       1800    IN      SOA     major.ns.cloudflare.com. dns.cloudflare.com. 2329072653 10000 2400 604800 1800

;; Query time: 16 msec
;; SERVER: 2001:41d0:3:163::1#53(2001:41d0:3:163::1) (UDP)
;; WHEN: Fri Dec 29 19:33:51 UTC 2023
;; MSG SIZE  rcvd: 115
```

Home:

```
dig hyperlist.hyperspin-fe.com

; <<>> DiG 9.18.16-1~deb12u1-Debian <<>> hyperlist.hyperspin-fe.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 40467
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;hyperlist.hyperspin-fe.com.    IN      A

;; AUTHORITY SECTION:
hyperspin-fe.com.       1106    IN      SOA     major.ns.cloudflare.com. dns.cloudflare.com. 2329072653 10000 2400 604800 1800

;; Query time: 0 msec
;; SERVER: 192.168.1.252#53(192.168.1.252) (UDP)
;; WHEN: Fri Dec 29 19:34:42 WET 2023
;; MSG SIZE  rcvd: 115

ping hyperlist.hyperspin-fe.com
ping: hyperlist.hyperspin-fe.com: Name or service not known
```

**Comment by gantoine** [comment]
This has been fixed in the latest RC, and will be available in the upcoming release. Hyperspin has proven pretty unreliable (tends to go down often) so we've switched to using a simple gist that we update regularly.

**Comment by daedric7** [comment]
Great! dev-latest then? :)

**Comment by gantoine** [comment]
Yep that'll work!

**Comment by daedric7** [comment]
I don't think so:

```
romm     | INFO:          [RomM][2023-12-29 20:00:57]    · flyball.7z
romm     | INFO:          [RomM][2023-12-29 20:00:59]      Identified as Flyball 👾
romm     | INFO:          [RomM][2023-12-29 20:00:59]    · tophuntr.7z
romm     | ERROR:         [RomM][2023-12-29 20:01:02] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/covers/
romm     | ERROR:         [RomM][2023-12-29 20:01:02] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/screenshots/
romm     | WARNING:  [RomM][2023-12-29 20:01:02]           tophuntr.7z not found in IGDB
romm     | INFO:          [RomM][2023-12-29 20:01:02]    · m5croclb.7z
romm     | ERROR:         [RomM][2023-12-29 20:01:04] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/covers/
romm     | ERROR:         [RomM][2023-12-29 20:01:05] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/screenshots/
romm     | WARNING:  [RomM][2023-12-29 20:01:05]           m5croclb.7z not found in IGDB
romm     | INFO:          [RomM][2023-12-29 20:01:05]    · cottonbm.7z
romm     | ERROR:         [RomM][2023-12-29 20:01:08] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/covers/
romm     | ERROR:         [RomM][2023-12-29 20:01:08] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/screenshots/
romm     | WARNING:  [RomM][2023-12-29 20:01:08]           cottonbm.7z not found in IGDB
romm     | INFO:          [RomM][2023-12-29 20:01:08]    · mjyougo.7z
romm     | ERROR:         [RomM][2023-12-29 20:01:11] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/covers/
romm     | ERROR:         [RomM][2023-12-29 20:01:12] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/screenshots/
romm     | WARNING:  [RomM][2023-12-29 20:01:12]           mjyougo.7z not found in IGDB
romm     | INFO:          [RomM][2023-12-29 20:01:12]    · grgar_l1.7z
```

**Comment by gantoine** [comment]
Can you go into settings and manually run all the tasks? There should be a button for it in the UI.

**Comment by zurdi15** [comment]
> Can you go into settings and manually run all the tasks? There should be a button for it in the UI.

True, this is for updating the `xml` that now is being fetch from the gist

**Comment by gantoine** [comment]
If you want to verify that it downloaded it correctly you can exec into the container and look for the file `mame.xml` under `/handler/fixtures`

**Comment by daedric7** [comment]
Uhm... 

```
d4c9af098d44:/backend/handler/fixtures# ls
ps2_opl_index.json
```

All the tasks buttons are greyed out :/

**Comment by gantoine** [comment]
hmmmm is `ENABLE_SCHEDULED_UPDATE_MAME_XML=true` set in your .env? and can you post a screenshot of the button?

**Comment by daedric7** [comment]
No .env for me, all in docker-compose:

```
   # [Optional] Will enable asynchronous tasks (all disabled by default)
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=true # Runs a quick scan on the library when a file is added or removed
      - RESCAN_ON_FILESYSTEM_CHANGE_DELAY=5 # Delay in seconds before running the quick scan (default: 5)
      - ENABLE_SCHEDULED_RESCAN=true # Runs a quick scan on the library at a given time
      - SCHEDULED_RESCAN_CRON=0 3 * * * # Cron expression for the scheduled scan (default: 0 3 * * * - At 3:00 AM every day)
      - ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB=true # Updates the Switch TitleDB database at a given time
      - SCHEDULED_UPDATE_SWITCH_TITLEDB_CRON=0 4 * * * # Cron expression for the scheduled update (default: 0 4 * * * - At 4:00 AM every day)
      - ENABLE_SCHEDULED_UPDATE_MAME_XML=true # Updates the MAME XML database at a given time
      - SCHEDULED_UPDATE_MAME_XML_CRON=0 5 * * * # Cron expression for the scheduled update (default: 0 5 * * * - At 5:00 AM every day)

```

![image](https://github.com/zurdi15/romm/assets/4562461/cccf932d-4e3a-4949-af4a-d4ecbcd86e02)

**Comment by gantoine** [comment]
hmmm they're all disabled in the UI, can you post the entire docker-compose section for romm?

**Comment by daedric7** [comment]
Sure:

```
version: "3"
services:
  romm:
    image: zurdi15/romm:dev-latest
    container_name: romm
    environment:
      - ROMM_DB_DRIVER=mariadb # mariadb | sqlite (default: sqlite)
      # [Optional] Only required if using MariaDB as the database
      - DB_HOST=romm_db
      - DB_PORT=3306
      - DB_USER=
      - DB_NAME=# Should match the MYSQL_DATABASE value in the mariadb container
      - DB_PASSWD=
      - IGDB_CLIENT_ID=
      - IGDB_CLIENT_SECRET=
      # [Optional - WIP] Use SteamGridDB as a source for covers
      - STEAMGRIDDB_API_KEY=
      # [Optional] Will enable user management and require authentication to access the interface (disabled by default)
      - ROMM_AUTH_ENABLED=true # default: false
      - ROMM_AUTH_SECRET_KEY= # Generate a key with `openssl rand -hex 32`
      - ROMM_AUTH_USERNAME=# default: admin
      - ROMM_AUTH_PASSWORD= # default: admin
      # [Optional] Only required if authentication is enabled
      - ENABLE_EXPERIMENTAL_REDIS=true # default: false
      - REDIS_HOST=redis_romms # default: localhost
      - REDIS_PORT=6379 # default: 6379
      #- REDIS_PASSWORD=<redis password> # [Optional] Support for secured redis
      # [Optional] Will enable asynchronous tasks (all disabled by default)
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=true # Runs a quick scan on the library when a file is added or removed
      - RESCAN_ON_FILESYSTEM_CHANGE_DELAY=5 # Delay in seconds before running the quick scan (default: 5)
      - ENABLE_SCHEDULED_RESCAN=true # Runs a quick scan on the library at a given time
      - SCHEDULED_RESCAN_CRON=0 3 * * * # Cron expression for the scheduled scan (default: 0 3 * * * - At 3:00 AM every day)
      - ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB=true # Updates the Switch TitleDB database at a given time
      - SCHEDULED_UPDATE_SWITCH_TITLEDB_CRON=0 4 * * * # Cron expression for the scheduled update (default: 0 4 * * * - At 4:00 AM every day)
      - ENABLE_SCHEDULED_UPDATE_MAME_XML=true # Updates the MAME XML database at a given time
      - SCHEDULED_UPDATE_MAME_XML_CRON=0 5 * * * # Cron expression for the scheduled update (default: 0 5 * * * - At 5:00 AM every day)
    volumes:
      - "/share/roms:/romm/library/roms"
      - "./resources:/romm/resources" # [Optional] Path where roms metadata (covers) are stored
      - "./config/config.yml:/romm/config.yml" # [Optional] Path where config is stored
      - "./database:/romm/database" # [Optional] Only needed if ROMM_DB_DRIVER=sqlite or not set
      - "./logs:/romm/logs" # [Optional] Path where logs are stored
    depends_on:
      - romm_db
    restart: "unless-stopped"
    networks:
      - npm-nw


  # [Optional] Only required if using MariaDB as the database
  romm_db:
    image: mariadb:latest
    container_name: romm_db
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    volumes:
      - ./mysql_data:/var/lib/mysql # Can also be mounted locally
    restart: "unless-stopped"
    networks:
      - npm-nw


  # [Optional] Only required if experimental Redis is enabled
  redis_romms:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - npm-nw

networks:
  npm-nw:
    external: true

```
