### ISSUE TITLE
Cannot log in, 200 then 403 within console output

### ISSUE THREAD

**Issue by is33** [zurdi15/romm#606]
**RomM version**
Latest ast of 1-15

**Describe the bug**
200 then 403 when logging in - confirmed correct login within config

**To Reproduce**
Fresh reinstall

**Expected behavior**
logging in and getting to app

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Server on ubuntu, web on linux
 - Browser Chrome 
 - Version latest

**Smartphone (please complete the following information):**

**Additional context**
output from docker compose:
```

romm       | INFO:      - "POST /login HTTP/1.0" 401 Unauthorized
romm       | INFO:        [nginx][2024-01-15 20:31:36]  192.168.1.114 - - "POST /api/login HTTP/1.1" 401 43 "http://192.168.1.83/login?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" rt=0.006 uct="0.000" uht="0.007" urt="0.007"
romm       | INFO:      - "POST /login HTTP/1.0" 200 OK
romm       | INFO:        [nginx][2024-01-15 20:31:43]  192.168.1.114 - admin "POST /api/login HTTP/1.1" 200 36 "http://192.168.1.83/login?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" rt=0.311 uct="0.000" uht="0.311" urt="0.311"
romm       | INFO:      - "GET /roms-recent HTTP/1.0" 403 Forbidden
romm       | INFO:        [nginx][2024-01-15 20:31:43]  192.168.1.114 - - "GET /api/roms-recent HTTP/1.1" 403 22 "http://192.168.1.83/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" rt=0.002 uct="0.000" uht="0.003" urt="0.003"
romm       | INFO:      - "GET /platforms HTTP/1.0" 403 Forbidden
romm       | INFO:        [nginx][2024-01-15 20:31:43]  192.168.1.114 - - "GET /api/platforms HTTP/1.1" 403 22 "http://192.168.1.83/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" rt=0.010 uct="0.000" uht="0.009" urt="0.009"
```

Config with redactions:
```
version: "3"
volumes:
  mysql_data:
services:
  romm:
    image: zurdi15/romm:latest
    container_name: romm
    environment:
      - ROMM_DB_DRIVER=mariadb # mariadb | sqlite (default: sqlite)
      - ROMM_HOST=https://localhost:3000 # [Optional] your host ip or domain name (including http(s)://, subdomain and port if needed). Being used >      # [Optional] Only required if using MariaDB as the database
      - DB_HOST=romm_db
      - DB_PORT=3306
      - DB_USER=romm-user
      - DB_NAME=romm # Should match the MYSQL_DATABASE value in the mariadb container
      - DB_PASSWD=[secure password]
      - IGDB_CLIENT_ID=[redacted]
      - IGDB_CLIENT_SECRET=[redacted]
      # [Optional - WIP] Use SteamGridDB as a source for covers
      # - STEAMGRIDDB_API_KEY=<SteamGridDB api key>
      # [Optional] Will enable user management and require authentication to access the interface (disabled by default)
      - ROMM_AUTH_ENABLED=true # default: false
      - ROMM_AUTH_SECRET_KEY=[redacted] # Generate a key with `openssl rand -hex 32`
      - ROMM_AUTH_USERNAME=admin # default: admin
      - ROMM_AUTH_PASSWORD=[redacted] # default: admin
      # [Optional] Only required if authentication is enabled
      - ENABLE_EXPERIMENTAL_REDIS=false # default: false
      - REDIS_HOST=redis # default: localhost
      - REDIS_PORT=6379 # default: 6379
      #- REDIS_PASSWORD=[redacted] # [Optional] Support for secured redis
      # [Optional] Will enable asynchronous tasks (all disabled by default)
      # Important: Do NOT wrap the cron expression in quotes
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=true # Runs a quick scan on the library when a file is added or removed
      - RESCAN_ON_FILESYSTEM_CHANGE_DELAY=5 # Delay in seconds before running the quick scan (default: 5)
      - ENABLE_SCHEDULED_RESCAN=true # Runs a quick scan on the library at a given time
      - SCHEDULED_RESCAN_CRON=0 3 * * * # Cron expression for the scheduled scan (default: 0 3 * * * - At 3:00 AM every day)
      - ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB=true # Updates the Switch TitleDB database at a given time
      - SCHEDULED_UPDATE_SWITCH_TITLEDB_CRON=0 4 * * * # Cron expression for the scheduled update (default: 0 4 * * * - At 4:00 AM every day)
      - ENABLE_SCHEDULED_UPDATE_MAME_XML=true # Updates the MAME XML database at a given time
      - SCHEDULED_UPDATE_MAME_XML_CRON=0 5 * * * # Cron expression for the scheduled update (default: 0 5 * * * - At 5:00 AM every day)
    volumes:
      - "/romm/library:/romm/library"
      - "/romm/resources:/romm/resources" # [Optional] Path where roms metadata (covers) are stored
      - "/romm/config/config.yml:/romm/config.yml" # [Optional] Path where config is stored
      - "/romm/database:/romm/database" # [Optional] Only needed if ROMM_DB_DRIVER=sqlite or not set
      - "/romm/logs:/romm/logs" # [Optional] Path where logs are stored
    ports:
      - 80:8080
    depends_on:
      - romm_db
    restart: "unless-stopped"

  # [Optional] Only required if using MariaDB as the database
  romm_db:
    image: mariadb:latest
    container_name: romm_db
    environment:
      - MYSQL_ROOT_PASSWORD=[redacted]
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=[redacted]
    volumes:
      - mysql_data:/var/lib/mysql # Can also be mounted locally
    ports:
      - 3306:3306
    restart: "unless-stopped"

  # [Optional] Only required if experimental Redis is enabled
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
```
