### ISSUE TITLE
config.yml is directory?

### ISSUE THREAD

**Issue by is33** [zurdi15/romm#607]
Attempting to re-deploy after I broke the system hard. When I try and deploy with config below, docker is stating config.yml is a directory.

```
exclude:
  # Exclude platforms to be scanned
  platforms:
    - 'romm'

  # Exclude roms or parts of roms to be scanned
  roms:

    ## Single file games section.
    # Will not apply to files that are in sub-folders (multi-disc roms, games with updates, DLC, patches, etc.)
    single_file:
      # Exclude all files with certain extensions to be scanned
      extensions:
        - 'xml'
      # Exclude matched file names to be scanned
      names:
        - 'info.txt'
        - '._*' # Supports unix filename pattern matching
        - '*.nfo' # Can also exclude files by extension

    ## Multi files games section
    # Will apply to files that are in sub-folders (multi-disc roms, games with updates, DLC, patches, etc.)
    multi_file:
      # Exclude matched 'folder' names to be scanned (RomM identifies folders as multi file games)
      names:
        - 'my_multi_file_game'
        - 'DLC'
      # Exclude files within sub-folders.
      parts:
        # Exclude matched file names to be scanned from multi file roms
        # Keep in mind that RomM doesn't scan folders inside multi files games,
        # so there is no need to exclude folders from inside of multi files games.
        names:
          - 'data.xml'
          - '._*' # Supports unix filename pattern matching
        # Exclude all files with certain extensions to be scanned from multi file roms
        extensions:
          - 'txt'

# Associate different platform names to your current file system platform names
system:
  platforms:
    # [your custom platform folder name]: [RomM platform name]
    gc: 'ngc' # In this example if you have a 'gc' folder, RomM will treat it like the 'ngc' folder
    psx: 'ps' # In this example if you have a 'psx' folder, RomM will treat it like the 'ps' folder
    nds: 'nds'
```

mapping:

![Screenshot 2024-01-16 005838](https://github.com/zurdi15/romm/assets/1373128/73e8898c-d83c-4cb0-a717-43d1e91a2e85)

compose file:

```
version: "3"
volumes:
  mysql_data:
services:
  romm:
    image: zurdi15/romm:latest
    container_name: romm
    environment:
      - ROMM_DB_DRIVER=mariadb # mariadb | sqlite (default: sqlite)
      - ROMM_HOST=https://localhost:3000 # [Optional] your host ip or domain name (including http(s)://, subdomain and port if needed). Being used only for webRcade feed for now.
      # [Optional] Only required if using MariaDB as the database
      - DB_HOST=romm_db
      - DB_PORT=3306
      - DB_USER=romm-user
      - DB_NAME=romm # Should match the MYSQL_DATABASE value in the mariadb container
      - DB_PASSWD=[redacted]
      - IGDB_CLIENT_ID=[redacted]
      - IGDB_CLIENT_SECRET=[redacted]
      # [Optional - WIP] Use SteamGridDB as a source for covers
      # - STEAMGRIDDB_API_KEY=<SteamGridDB api key>
      # [Optional] Will enable user management and require authentication to access the interface (disabled by default)
      - ROMM_AUTH_ENABLED=true # default: false
      - ROMM_AUTH_SECRET_KEY=[redacted] # Generate a key with `openssl rand -hex 32`
      - ROMM_AUTH_USERNAME=admin # default: admin
      - ROMM_AUTH_PASSWORD=[redacted] # default: admin
      # [Optional] Only required if authentication is enabled
      - ENABLE_EXPERIMENTAL_REDIS=true # default: false
      - REDIS_HOST=localhost # default: localhost
      - REDIS_PORT=6379 # default: 6379
      - REDIS_PASSWORD=[redacted] # [Optional] Support for secured redis
      # [Optional] Will enable asynchronous tasks (all disabled by default)
      # Important: Do NOT wrap the cron expression in quotes
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=true # Runs a quick scan on the library when a file is added or removed 
      - RESCAN_ON_FILESYSTEM_CHANGE_DELAY=5 # Delay in seconds before running the quick scan (default: 5)
      - ENABLE_SCHEDULED_RESCAN=true # Runs a quick scan on the library at a given time
      - SCHEDULED_RESCAN_CRON=0 3 * * * # Cron expression for the scheduled scan (default: 0 3 * * * - At 3:00 AM every day)
      - ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB=true # Updates the Switch TitleDB database at a given time
      - SCHEDULED_UPDATE_SWITCH_TITLEDB_CRON=0 4 * * * # Cron expression for the scheduled update (default: 0 4 * * * - At 4:00 AM every day)
      - ENABLE_SCHEDULED_UPDATE_MAME_XML=true # Updates the MAME XML database at a given time
      - SCHEDULED_UPDATE_MAME_XML_CRON=0 5 * * * # Cron expression for the scheduled update (default: 0 5 * * * - At 5:00 AM every day)
    volumes:
      - "/rom/library:/romm/library"
      - "/rom/resources:/romm/resources" # [Optional] Path where roms metadata (covers) are stored
      - "/rom/config/config.yml:/romm/config.yml" # [Optional] Path where config is stored
      - "/rom/database:/romm/database" # [Optional] Only needed if ROMM_DB_DRIVER=sqlite or not set
      - "/rom/logs:/romm/logs" # [Optional] Path where logs are stored
    ports:
      - 80:8080
    depends_on:
      - romm_db
    restart: "unless-stopped"

  # [Optional] Only required if using MariaDB as the database
  romm_db:
    image: mariadb:latest
    container_name: romm_db
    environment:
      - MYSQL_ROOT_PASSWORD=[redacted]
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=[redacted]
    volumes:
      - mysql_data:/var/lib/mysql # Can also be mounted locally
    ports:
      - 3306:3306
    restart: "unless-stopped"

  # [Optional] Only required if experimental Redis is enabled
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
```

**Comment by zurdi15** [comment]
Can you share the logs? Everything seems fine to me

**Comment by gantoine** [comment]
That likely means docker can't read the file due to permissions, or `/rom/config/config.yml` isn't where the file is located.

**Comment by is33** [comment]
Interestingly, when I deploy outside of portainer (docker-compose), it works....kinda, config tab doesn't load. However, the rest loads fine (working through some what I think is unrelated issues within scanning, not picking up .gba files)
Logs per request

[Portainer.txt](https://github.com/zurdi15/romm/files/13951730/Portainer.txt)
[dockercompose.txt](https://github.com/zurdi15/romm/files/13951731/dockercompose.txt)

**Comment by is33** [comment]
Adding, I did notice a differential in docker-compose. Updated so both are running the below config. Same issue


```
version: "3"
volumes:
  mysql_data:
services:
  romm:
    image: zurdi15/romm:latest
    container_name: romm
    environment:
      - ROMM_DB_DRIVER=mariadb # mariadb | sqlite (default: sqlite)
      - ROMM_HOST=https://localhost:3000 # [Optional] your host ip or domain name (including http(s)://, subdomain and port if needed). Being used only for webRcade feed for now.
      # [Optional] Only required if using MariaDB as the database
      - DB_HOST=romm_db
      - DB_PORT=3306
      - DB_USER=romm-user
      - DB_NAME=romm # Should match the MYSQL_DATABASE value in the mariadb container
      - DB_PASSWD=[redacted] 
      - IGDB_CLIENT_ID=[redacted] 
      - IGDB_CLIENT_SECRET=[redacted] 
      # [Optional - WIP] Use SteamGridDB as a source for covers
      # - STEAMGRIDDB_API_KEY=<SteamGridDB api key>
      # [Optional] Will enable user management and require authentication to access the interface (disabled by default)
      - ROMM_AUTH_ENABLED=false # default: false
      - ROMM_AUTH_SECRET_KEY=[redacted]  # Generate a key with `openssl rand -hex 32`
      - ROMM_AUTH_USERNAME=admin # default: admin
      - ROMM_AUTH_PASSWORD=[redacted]  # default: admin
      # [Optional] Only required if authentication is enabled
      - ENABLE_EXPERIMENTAL_REDIS=false # default: false
      - REDIS_HOST=redis # default: localhost
      - REDIS_PORT=6379 # default: 6379
      - REDIS_PASSWORD=[redacted] # [Optional] Support for secured redis
      # [Optional] Will enable asynchronous tasks (all disabled by default)
      # Important: Do NOT wrap the cron expression in quotes
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=true # Runs a quick scan on the library when a file is added or removed
      - RESCAN_ON_FILESYSTEM_CHANGE_DELAY=5 # Delay in seconds before running the quick scan (default: 5)
      - ENABLE_SCHEDULED_RESCAN=true # Runs a quick scan on the library at a given time
      - SCHEDULED_RESCAN_CRON=0 3 * * * # Cron expression for the scheduled scan (default: 0 3 * * * - At 3:00 AM every day)
      - ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB=true # Updates the Switch TitleDB database at a given time
      - SCHEDULED_UPDATE_SWITCH_TITLEDB_CRON=0 4 * * * # Cron expression for the scheduled update (default: 0 4 * * * - At 4:00 AM every day)
      - ENABLE_SCHEDULED_UPDATE_MAME_XML=true # Updates the MAME XML database at a given time
      - SCHEDULED_UPDATE_MAME_XML_CRON=0 5 * * * # Cron expression for the scheduled update (default: 0 5 * * * - At 5:00 AM every day)
    volumes:
      - "/rom/library:/romm/library"
      - "/rom/resources:/romm/resources" # [Optional] Path where roms metadata (covers) are stored
      - "/rom/config/config.yml:/romm/config.yml" # [Optional] Path where config is stored
      - "/rom/database:/romm/database" # [Optional] Only needed if ROMM_DB_DRIVER=sqlite or not set
      - "/rom/logs:/romm/logs" # [Optional] Path where logs are stored
    ports:
      - 80:8080
    depends_on:
      - romm_db
    restart: "unless-stopped"

  # [Optional] Only required if using MariaDB as the database
  romm_db:
    image: mariadb:latest
    container_name: romm_db
    environment:
      - MYSQL_ROOT_PASSWORD=[redacted] 
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=[redacted] 
    volumes:
      - mysql_data:/var/lib/mysql # Can also be mounted locally
    ports:
      - 3306:3306
    restart: "unless-stopped"

  # [Optional] Only required if experimental Redis is enabled
#  redis:
#    image: redis:alpine
#    container_name: redis
#    restart: unless-stopped
#    ports:
#      - 6379:6379
```
