### ISSUE TITLE
[Feature] ENV to define config.yml location

### ISSUE THREAD

**Issue by webysther** [zurdi15/romm#609]
**Describe the solution you'd like**
I use named docker volumes and is not possible to mount a file when using NFS/SMB, is possible to create a ENV VAR to change the location of config.yml to allow put in any other random folder?

**Comment by gantoine** [comment]
Just so I understand clearly, could you make up an example of how the docker-compose would look/how you would mount config.yml?

**Comment by webysther** [comment]
> Just so I understand clearly, could you make up an example of how the docker-compose would look/how you would mount config.yml?

Sure:

```yml
services:
  romm:
    image: zurdi15/romm:latest
    container_name: romm
    environment:
      # [Optional] Only if you want to change the default config.yml location
      - ROMM_CONFIG_PATH=/romm/config/config.yml
    volumes:
      - "/path/to/config:/romm/config:ro" # [Optional] Path where config is stored
```

The `/path/to/config` has the `config.yml` inside

**Comment by zurdi15** [comment]
Ahh understood, so you mean changing the internal path of where the config is being stored through an `env` variable because you can't mound files directly, just folders?

**Comment by webysther** [comment]
> Ahh understood, so you mean changing the internal path of where the config is being stored through an `env` variable because you can't mound files directly, just folders?

Yeap, because docker with named volume don't permit direct files. But this can extend the application to have more configuration files in the future and give more flexibility. :)

To fast fix this in my case I just mount every platform rom folder as expected by romm and I don't need to use the config, but this is how the final mount looks like:

```yaml
    volumes:
      - resource:/romm/resources
      - db:/romm/database
      - log:/romm/logs
      # roms
      - rom-3do:/romm/library/3do/roms:ro
      - rom-arcade:/romm/library/arcade/roms:ro
      - rom-atari2600:/romm/library/atari2600/roms:ro
      - rom-gb:/romm/library/gb/roms:ro
      - rom-gba:/romm/library/gba/roms:ro
      - rom-n64:/romm/library/n64/roms:ro
      - rom-nds:/romm/library/nds/roms:ro
      - rom-nes:/romm/library/nes/roms:ro
      - rom-snes:/romm/library/snes/roms:ro
      - rom-psx:/romm/library/ps/roms:ro
      - rom-pce:/romm/library/turbografx-16-slash-pc-engine-cd/roms:ro
      - rom-segamd:/romm/library/genesis-slash-megadrive/roms:ro
      - rom-segasg:/romm/library/sg1000/roms:ro
      - rom-segasaturn:/romm/library/saturn/roms:ro
      - rom-doom:/romm/library/dos/roms:ro

volumes:
  rom-3do:
    name: "$STACK-rom-3do"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/3do/roms"
  rom-arcade:
    name: "$STACK-rom-arcade"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/arcade/roms"
  rom-atari2600:
    name: "$STACK-rom-atari2600"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/atari2600/roms"
  rom-gb:
    name: "$STACK-rom-gb"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/gb/roms"
  rom-gba:
    name: "$STACK-rom-gba"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/gba/roms"
  rom-n64:
    name: "$STACK-rom-n64"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/n64/roms"
  rom-nds:
    name: "$STACK-rom-nds"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/nds/roms"
  rom-nes:
    name: "$STACK-rom-nes"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/nes/roms"
  rom-snes:
    name: "$STACK-rom-snes"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/snes/roms"
  rom-psx:
    name: "$STACK-rom-psx"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/psx/roms"
  rom-pce:
    name: "$STACK-rom-pce"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/pce/roms"
  rom-segamd:
    name: "$STACK-rom-segamd"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/segaMD/roms"
  rom-segasg:
    name: "$STACK-rom-segasg"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/segaSG/roms"
  rom-segasaturn:
    name: "$STACK-rom-segasaturn"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/segaSaturn/roms"
  rom-doom:
    name: "$STACK-rom-doom"
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/emulatorjs/data/doom/roms"
```
